name: Helios Traceker AWS Lambda Deployment
run-name: ${{ github.actor }} is deploying HeliosTracker to AWS 🚀


on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Set up HeliosTracker repository
      uses: actions/checkout@v3
      with:
        path: heliostracker

    - name: Set up ConEd repository
      uses: actions/checkout@v3
      with:
        repository: varming/coned
        path: coned

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        architecture: 'x64'
        python-version: '3.x'
        cache: pip
        cache-dependency-path: |
          **/requirements*.txt

    - name: Fetch Python dependencies
      run: |
        pip install -r coned/requirements.txt
        pip install -r heliostracker/requirements.txt

    - name: Configure AWS
      run: |
        set -eu -o pipefail
        umask 177
        export AWS_ROLE_ARN=arn:aws:iam::162141084993:role/GithubActions
        export AWS_WEB_IDENTITY_TOKEN_FILE=$(mktemp -q awscreds.XXXXXX)
        export AWS_DEFAULT_REGION=us-east-1
        echo AWS_WEB_IDENTITY_TOKEN_FILE=$AWS_WEB_IDENTITY_TOKEN_FILE >> $GITHUB_ENV
        echo AWS_ROLE_ARN=$AWS_ROLE_ARN >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $GITHUB_ENV
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

    - run: aws sts get-caller-identity

